# Generated by Django 4.2 on 2023-04-20 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="empleados",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=40)),
                ("entrada", models.DateTimeField()),
                ("exit_time", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="proovedor",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=40)),
                ("identidad", models.CharField(max_length=50)),
            ],
        ),
    ]
