# Generated by Django 4.2 on 2023-04-20 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("empleados", "0002_alter_empleados_id_alter_proovedor_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="proovedor",
        ),
        migrations.RenameField(
            model_name="empleados",
            old_name="exit_time",
            new_name="salida",
        ),
    ]
